---
title: "Plotly_hw4_Q2"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Dataset

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

## Relevant Plots

This plot is a representation of the total number of ordered items per aisle.

```{r}
data(instacart)
order_aisle_insta = 
  instacart %>%
  group_by(aisle) %>%
  summarize(total = n()) %>%
  arrange(desc(total)) %>%
  filter(total > 10000) %>%
  mutate(aisle = fct_reorder(aisle, total)) %>%
  plot_ly(x = ~aisle, y = ~total, colors = ~aisle, type = "bar", alpha = 0.5)
  ggplotly(order_aisle_insta)
```
This plot represents a distribution of the hour of day for orders of Pink Lady Apples and Coffee Ice Cream respectively.

```{r}
order_hour_insta = 
  instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  plot_ly(y = ~order_hour_of_day, color = ~product_name, type = "box", colors = "viridis")
ggplotly(order_hour_insta)
```

This histogram demonstrates the relationship between order hour and the day for Pink Lady Apples and Coffee Ice Cream respectively.

```{r}
order_day_insta = 
  instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  plot_ly(x = ~order_hour_of_day, y = ~order_dow, color = ~product_name, type = "histogram")
ggplotly(order_day_insta)
```